### PR TITLE
open gmail

### PR DESCRIPTION
**Pull request by speedy-software-ch**

### CODE REVIEW

**Comment by ritwik12** [comment]
@speedy-software-ch Your code is not opening Gmail in my system i.e Ubuntu 15.04.
Please make it work for all systems

**Comment by speedy-software-ch** [comment]
ok. i'll do. but only next year. lol

**Comment by speedy-software-ch** [comment]
@ritwik12 could you try to install the package "gnome-gmail" with apt-get install gnome-gmail   ?

**Comment by ritwik12** [comment]
@speedy-software-ch I already did.It just opens the web browser without any website.

**Comment by speedy-software-ch** [comment]
@ritwik12 are you sure? not even google or something in this direction?

**Comment by ritwik12** [comment]
@speedy-software-ch Nothing at all, it opens browser and keeps loading the tab.then at the end it's just a blank tab

**Pull request closed without merging**
