### PR TITLE
Fixed issue with dependency on libjson0 and libjson0-dev in main.c and README.md

### PR DESCRIPTION
**Pull request by ellisken**
#33 
Updated main.c headers to match libjson-c-dev and updated libjson install statement and compile instructions in README.

### CODE REVIEW

**Comment by ritwik12** [comment]
@ellisken Hey, thanks for your PR. But I won't be able to look into this for few days as I'm traveling right now. I'll reply ASAP.

**Comment by ritwik12** [comment]
@ellisken Thanks!!

**Comment by ellisken** [comment]
Thanks for the merge!

**Comment by ritwik12** [comment]
@ellisken Thanks for your contribution.

**Pull request merged**
