### PR TITLE
Fix nested if else

### PR DESCRIPTION
**Pull request by harrywaugh**
Think this fixes the issue I raised yesterday, I know your busy so don't rush to merge anything. Thanks!

### CODE REVIEW

**Comment by ritwik12** [comment]
@hw16471 This looks good, I will surely merge this ASAP. Thanks for sending PR.

**Comment by ritwik12** [comment]
@hw16471 I agree with @speedy-software-ch

**Comment by hw16471** [comment]
Ah ofc, apologies forgot to update highest score in the if statement, should be fine now

**Comment by ritwik12** [comment]
@hw16471 Thanks for your PR, I have tested your code and it is failing while comparisons.
Try to type ".", or any alphabet. It is not working for that.

**Comment by ritwik12** [comment]
Closing this due to lack of Activity!!

**Pull request closed without merging**
