### PR TITLE
Math operations

### PR DESCRIPTION
**Pull request by Eldart95**

### CODE REVIEW

**Comment by ritwik12** [comment]
@Eldart95 THanks for sending the PR, In addition to this, we would need classification changes also for the MATH category. Please add that too

**Comment by Eldart95** [comment]
hey, i updated the classifiers yet the NLC dosent seem to work, can u please review the last commit and see if u can find out what is the problem ?
thanks.

**Comment by ritwik12** [comment]
@Eldart95 For that I think you will have to change analysis.c also and need to make additional for loops for comparisons and it could be a long work.

If you want you can keep this as simple as the calendar, youtube and help functionalities.
We don't use the NLP part for these categories and use exact words or commands only. like for HELP we use only 'help' and for calendar we use 'open calendar' not the normal language. You can check the working of those and define it in same way only.

**Comment by ritwik12** [comment]
@Eldart95 I think previously u did the same thing only. We can keep it that way also based on your choice.

**Comment by Eldart95** [comment]
i think that keeping the math operations simple is fine, due to the fact that its a specific task.
i re-defined the classifiers , hows that now ?

**Comment by ritwik12** [comment]
@Eldart95 Thanks a lot for your PR!!

**Comment by ritwik12** [comment]
@all-contributors please add @Eldart95 for code and doc

**Pull request merged**
