### PR TITLE
Added Home Directory into a config File

### PR DESCRIPTION
**Pull request by speedy-software-ch**
And added an example config file. No need to hardcode it that way.

### CODE REVIEW

**Comment by ritwik12** [comment]
@speedy-software-ch I can't understand what it does. please elaborate.

**Comment by speedy-software-ch** [comment]
I outsourced the home directory to a string from a file named "config*. so you don't need to change it in hardcoded source code. it is being used for songs folder, and help file display.

**Comment by ritwik12** [comment]
@speedy-software-ch Ohk I get it now, Thanks

**Comment by ritwik12** [comment]
@speedy-software-ch Great work 👍

**Comment by speedy-software-ch** [comment]
ok, cool work but no merge?

**Comment by ritwik12** [comment]
@speedy-software-ch Changes are requested, please make the changes before I merge.

**Comment by speedy-software-ch** [comment]
which changes?

**Comment by ritwik12** [comment]
@speedy-software-ch  Please look in the conversation or file changes.
I asked you to make  changes regarding this 
capture

and a few more

**Comment by speedy-software-ch** [comment]
i don't see them. where should they appear?

**Comment by ritwik12** [comment]
@speedy-software-ch  I think you are new to github.
Here have a look 
capture

**Comment by speedy-software-ch** [comment]
screenshot from 2017-10-30 19-11-09

**Comment by ritwik12** [comment]
@speedy-software-ch I don't know why you can't see it.
Well I'll again review.

1. please change "isai" to "ritwik" or "username" in config file.
2. line 25 It will be `cfg_line[i-1].`
    I executed the program and it wasn't working with `i-2.`
    It was not able to find the directory properly.
    It gave following error
    > ls: cannot access /home/isai/Virtual-Assistant/Virtual-Assistantmedia/: No such file or directory
3.  line 122 why cvlc?
It is not working for me. Only vlc is working.
I think it's OS dependent.
Please change to vlc

**Comment by ritwik12** [comment]
@speedy-software-ch I don't know why you can't see it.
Well I'll again review.

1. please change "isai" to "ritwik" or "username" in config file.
2. line 25 It will be `cfg_line[i-1].`
    I executed the program and it wasn't working with `i-2.`
    It was not able to find the directory properly.
    It gave following error
    > ls: cannot access /home/isai/Virtual-Assistant/Virtual-Assistantmedia/: No such file or directory
3.  line 122 why cvlc?
It is not working for me. Only vlc is working.
I think it's OS dependent.
Please change to vlc

**Comment by ritwik12** [comment]
@speedy-software-ch  `HOME_DIR = HOME_DIR+2;` that was right.

**Comment by ritwik12** [comment]
@speedy-software-ch Thank you so much. sorry to trouble you.

**Comment by speedy-software-ch** [comment]
no problem. but does it really work for you like this?
I get error messages all over when trying to do something which involves the path

**Comment by ritwik12** [comment]
It was working for me when I tried.
I'll verify it once again tomorrow.
It's 4:20 am here. Gotta sleep

**Comment by speedy-software-ch** [comment]
do what you gotta do. added your time clock to my phones homescreen so i'll know when you could be active. 24.00 here

**Comment by ritwik12** [comment]
@speedy-software-ch Yes It is working fine, I am able to play media files.
You should check your config file and also you must be having the media directory with media files.

**Comment by speedy-software-ch** [comment]
i checked both, and still doesn't work. i get "permission denied" on media folder. what OS do you use, and maybe something to do with compiler?

**Comment by ritwik12** [comment]
@speedy-software-ch I once had that problem, I think it was vlc.
Are you able to open vlc by typing `vlc` in terminal?

**Comment by ritwik12** [comment]
@speedy-software-ch Ubuntu 15.04

**Comment by ritwik12** [comment]
@speedy-software-ch I am facing the issue that you are facing, I  had my files at location 
`HOME_DIR = /home/ritwik/Virtual-Assistant/Virtual-Assistant/` but when I shifted my files to Downloads directory, I got the same errrors. Don't know the issue yet.

**Comment by speedy-software-ch** [comment]
ok, could you maybe send the error message so i can compare with mine?

**Comment by ritwik12** [comment]
Same "permission denied"

**Pull request merged**
