### PR TITLE
Create makefile

### PR DESCRIPTION
**Pull request by hardikpnsp**
Created a simple make file to build and compile Virtual-Assistant

### Build: 
- Simply run `make`
- After making changes -> `make` should detect changes in the file and recompile only files that are changed

### Changes:
- New build directory is created `build` where all the object files `.o` and build file `virtual_assistant` is stored
- have added `build` directory in `.gitignore` 

closes: #73

### CODE REVIEW

**Comment by hardikpnsp** [comment]
Please test it and let me know if everything is working or not. Also, as we have a makefile, we might want to make changes in the compile section of `README.md` and maybe The CI pipeline too? I am not sure.

**Comment by ritwik12** [comment]
@hardikpnsp Thanks for sending PR, MakeFile works fine and does what you said. It is nice to have a Build directory separately. But I am unable to find an Executable after running `make`. Can you please tell me how can I do so?

Yes, we need to update Readme.md and CI Pipeline too. If you can do please go ahead.

**Comment by hardikpnsp** [comment]
The executable: `./build/virtual_assistant`

Sure, I will update Readme. Will also take a look at the CI.

**Comment by ritwik12** [comment]
That is giving me segmentation fault @hardikpnsp

**Comment by hardikpnsp** [comment]
> That is giving me segmentation fault @hardikpnsp

Oh, are you getting it right at the start? or at some particular point? for me, it works... can you try `make clean` and run it agian? also, what os are you using?

**Comment by hardikpnsp** [comment]
in the end, the `make` command will execute the following commands in order to build

```bash
mkdir -p build
gcc -c -o build/main.o main.c -std=gnu11 -Isrc -Iutils
gcc -c -o build/init_config.o src/init_config.c -std=gnu11 -Isrc -Iutils
gcc -o build/virtual_assistant build/main.o build/init_config.o -std=gnu11 -Isrc -Iutils -lssl -lcrypto -ljson-c `pkg-config --libs libcurl`
```
can the error be because of missing `--cflags` in the `pkg-config` at the end?

**Comment by ritwik12** [comment]
@hardikpnsp I think that has to do something with my certs in my system, sometimes this issue is their with librcurl in RHEL. Can you please check if your is working fine for the restaurant feature?

Try: "find places to eat"
And enter a location name like city when it asks for that.

**Comment by ritwik12** [comment]
@hardikpnsp Thanks for this contribution!!

**Comment by ritwik12** [comment]
@hardikpnsp Added you to the credits also for this.

**Comment by ritwik12** [comment]
@all-contributors please add @hardikpnsp for code

**Pull request merged**
