### PR TITLE
Added webbrowser configuration functionality to - out of config file,…

### PR DESCRIPTION
**Pull request by speedy-software-ch**
… as well as media player configuration (VLC doesn't work on my machine - Ubuntu 17.10).

Informing user about configuration options per voice on application start.

### CODE REVIEW

**Comment by speedy-software-ch** [comment]
I see you were more active than me lately. do you want to resolve this two conflicts created, or should i do?

**Comment by ritwik12** [comment]
@speedy-software-ch It's ohk, I'll do and merge.

**Comment by speedy-software-ch** [comment]
I think i did a preety good work on resolving the conflicts. could you check the changes please?

**Comment by speedy-software-ch** [comment]
for the future i'll try to find a way to stay up to date with upstream repository so that such stuff won't happen again. as well as look at your AI code. Could learn some new stuff and concepts just from looking at that code of you.

**Comment by ritwik12** [comment]
Yes, your conflicts are fine now.
I am using Travis CI for this purpose and it always resolves all the conflicts.I don't know why it happened this time.And you are always welcomed to add as much features as you want in this project.

**Comment by ritwik12** [comment]
@speedy-software-ch Everything is working great 👍.
Just one question, should we say preffered media and browser at the beginning or should we announce that only when user uses media player and browser respectively?
What do you think?

**Comment by speedy-software-ch** [comment]
because it's beeing parsed out of the config file at startup i would leave it there. at least for now

**Comment by ritwik12** [comment]
Alright

**Comment by ritwik12** [comment]
@speedy-software-ch Thanks :)

**Comment by speedy-software-ch** [comment]
what about libsprec for example found on github - it uses Google API

**Comment by speedy-software-ch** [comment]
??

**Pull request merged**
