### PR TITLE
Code Readablity

### PR DESCRIPTION
**Pull request by igo4Jesus**
This splits one long main file into five major components, also reducing the main function from 495 lines to 32 lines in the main file. This not only makes it easy to comment and study code, it also makes it easy to spot and kill bugs.

### CODE REVIEW

**Comment by ritwik12** [comment]
@igo4Jesus what you did is great. But ".h" (header files) are not made for this purpose. you should have different ".c" files instead of .h files. and they should be arranged hierarchically.

**Comment by ritwik12** [comment]
refer these repositories for how to maintain code. see they have lots of different files arranged in folders like "src", etc.
https://github.com/ritwik12/susi_server
https://github.com/Microsoft/winfile
https://github.com/reactos/reactos
https://www.quora.com/How-should-I-organize-GitHub-repositories-and-other-programming-related-files-1

Look at other good repos here
https://github.com/explore

**Comment by ritwik12** [comment]
@speedy-software-ch  Travis is failing because init_config file is renamed to init_config.c. I think it should remain .h only. What do you think @speedy-software-ch ?

**Comment by igo4Jesus** [comment]
That was why I did it that way, but U asked me to change it to c. I will make the changes as it was before now.. I pray it doesn't give any other issues, I'm running our of time, am supposed to submit my report today, but it looks like my contribution is of no effect cuz you haven't approved it yet... Please after these changes endorsed it.. Tnx

On 17 Apr 2018 7:36 pm, Ritwik Sharma <notifications@github.com> wrote:

@speedy-software-ch<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspeedy-software-ch&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7C247a0a202c2042cf568d08d5a47908fa%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636595762113418928&sdata=TtTnXoyqBCteulbFmj%2FIdc27h8KgqmyW2aJ299YLsMI%3D&reserved=0> Travis is failing because init_config file is renamed to init_config.c. I think it should remain .h only. What do you think @speedy-software-ch<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspeedy-software-ch&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7C247a0a202c2042cf568d08d5a47908fa%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636595762113418928&sdata=TtTnXoyqBCteulbFmj%2FIdc27h8KgqmyW2aJ299YLsMI%3D&reserved=0> ?

**Comment by speedy-software** [comment]
@igo4Jesus it failed again

**Comment by speedy-software** [comment]
@igo4Jesus again, i don't think .h files are meant to be used like that. we'll better change .travis.yml according to the C files added. and change Readme for how to compile. Or if there is no Makefile create one that represents the files that changed.

**Comment by ritwik12** [comment]
@igo4Jesus I think you got confused. I meant only "init_config.h" should be ".h" and all others should be ".c". there is no problem with travis. when you renamed all .h to .c it was correct. The problem was that in main.c we are including init_config.h but after you changed it to init_config.c .travis gave an error. Please change all files back to ".c" except "init_config.h"

**Comment by ritwik12** [comment]
@igo4Jesus By report what do you mean?

**Comment by igo4Jesus** [comment]
Never have I used github, but we have an open source course work where by we are to work on any open source community to grade us, itx 50% of our course work deadline has passed. With your username, my supervisor gat to check through my contribution and every progress, if you don't approved my contribution, I score 0%.. And I have to write a report on virtual-Assistat and the changes I made.. Middlesex University Mauritius

On 18 Apr 2018 7:12 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7Cdbf464ecfbb1454187dd08d5a53ebc11%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636596611216150951&sdata=mcTAnMuXO6T782T9SHSyldyhLUX2MvmKG99OX%2FMHNsU%3D&reserved=0> By report what do you mean?

**Comment by ritwik12** [comment]
@igo4Jesus Thanks for your contributions. It is a great contribution. Sorry for the delay but I wanted you to do all the changes. But you were getting late so I corrected all the things and merged it.

**Comment by igo4Jesus** [comment]
That shows I didn't contribute on the project.. I have to start all over again

On 18 Apr 2018 10:48 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7C43ada49ac0c94c55e33908d5a55cfb36%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636596741134056604&sdata=kvEwAaG354PgZc2WUgmuj1IdiXAKAyarjIQJ4gHSfj4%3D&reserved=0> Thanks for your contributions. It is a great contribution. Sorry for the delay but I wanted you to do all the changes. But you were getting late so I corrected all the things and merged it.

**Comment by ritwik12** [comment]
@igo4Jesus No, it's solely your contribution. I just changes the file names. You can see that.

**Comment by ritwik12** [comment]
Solved #17

**Comment by ritwik12** [comment]
@igo4Jesus Yes, I can give. How can I help?

**Comment by igo4Jesus** [comment]
Sending a note of confirmation via Gmail and on my pull requests.. Tnx so much

On 18 Apr 2018 11:06 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7Cb42350f8d76b46eecf6b08d5a55f88f3%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636596752117642476&sdata=OQEeINeScA0E0%2BHbDTAtHxAl9pRLEcXqCN%2Fwfk46%2FzM%3D&reserved=0> Yes, I can give. How can I help?

**Comment by ritwik12** [comment]
@igo4Jesus Thanks for your contributions. I look forward to getting more contributions from you in future.

**Comment by igo4Jesus** [comment]
Good day Ritwik, I wanna ask for a favour, please can you tell me more about this project, when it all started, the aim of it, how it will help our lives..

On 18 Apr 2018 11:54 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7CGI079%40live.mdx.ac.uk%7C2920cf9e5bf44eab815a08d5a5664274%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636596780980426693&sdata=VZSMcQmruaI2UHLL0R%2FbMJj35EjFnUdb1tE21Xila1A%3D&reserved=0> Thanks for your contributions. I look forward to getting more contributions from you in future.

**Comment by igo4Jesus** [comment]
Wow! That's great, tnx so much

On 20 Apr 2018 8:19 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7Cgi079%40live.mdx.ac.uk%7Ce844e1e33af44050db3b08d5a6da6eb0%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636598379457435642&sdata=Ug2w5jEwMPzED4zFkQI7lUUsMZG3QqSGEyaqKkLD7Xk%3D&reserved=0> Hey Goodluck, this project was started in September 2017 as part of my Minor 1 project of Btech in Computer Science and Engineering. This project won the first prize in the whole branch out of 76 students and 22 groups. Later being the first in my branch this project was selected for project expo in which all the first positions in all branches from a total of 13 branches and more than 1000 students and 200 groups. This project won the first prize in project expo too with a cash prize of 10,000 INR.
I moved this project to open source so that it could move further and help others to learn. This project is giving a nice response as open source.
Once it is fully complete this project will be able to control the whole Linux operating system with all the functionalities and it will help user in their all day to day personal tasks. This project could even be taken futher to cognitive AI in which it will be a self learning virtual assistant. So many functionalities could be added such as getting directions using google maps, playing videos on youtube, email anyone, speech to speech control by implementing Speech to text functionality, answering all user's question by fetching the answer from the internet such as "What is Github?" etc.

**Comment by ritwik12** [comment]
@all-contributors please add @igo4Jesus for code

**Comment by ritwik12** [comment]
@all-contributors please add @igo4Jesus for code

**Pull request merged**
