### PR TITLE
add files

### PR DESCRIPTION
**Pull request by igo4Jesus**
Contributing on code readability issue #17, Making the the code much simpler by making each functionality to be in a separate function. All done!

### CODE REVIEW

**Comment by ritwik12** [comment]
@igo4Jesus  analysis.h is missing

**Comment by ritwik12** [comment]
Also add the updated readme as I made some changes and yours is old one.

**Comment by ritwik12** [comment]
@Rushikesh22 @speedy-software-ch @riya-17 @danjod99 Please review this. As it is a big change in the code style.

**Comment by igo4Jesus** [comment]
I'm so sorry about that.... Please do I do as I did, or start all over again??

On 13 Apr 2018 5:24 pm, Ritwik Sharma <notifications@github.com> wrote:

@igo4Jesus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Figo4Jesus&data=02%7C01%7CGI079%40live.mdx.ac.uk%7C46e58a3a43784d681e5b08d5a141e856%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636592226808639603&sdata=j8khR2lgjAQ6ubOIkjuc2WFeI3oiGVpujdk5s9oD%2F1U%3D&reserved=0> analysis.h is missing

**Comment by ritwik12** [comment]
@igo4Jesus Just add analysis.h file to your fork repository.

**Comment by ritwik12** [comment]
@igo4Jesus whatever changes you will make in your fork will automatically reflect in your PR.

**Comment by ritwik12** [comment]
I too agree with @speedy-software....@igo4Jesus please refer other repositories for clearing this thing.

**Comment by ritwik12** [comment]
Closing this. completed in #31

**Pull request closed without merging**
