### PR TITLE
feat: add makefile [#73]

### LINKED ISSUE #73: Create a Makefile

### PR DESCRIPTION
**Pull request by mrneo240**
- adds a basic structure makefile
- should be easily human readable

fixes #73

### CODE REVIEW

**Comment by ritwik12** [comment]
Please mention here what it does and how can we use it @mrneo240

**Comment by mrneo240** [comment]
It's a makefile. You asked for it. 

run ``make`` and it will build your software. No need to manually call GCC anymore.

**Comment by ritwik12** [comment]
@mrneo240  I am not able to use it :( 
It is working for you?

**Comment by Sylk** [comment]
:( Sad.

**Comment by mrneo240** [comment]
Needs clarification

**Comment by ritwik12** [comment]
@mrneo240 It is not working for us :(

**Comment by ritwik12** [comment]
Closing against #99

**Pull request closed without merging**
