### PR TITLE
changed weather functionality from system("curl") way to the use of libcurl

### PR DESCRIPTION
**Pull request by speedy-software-ch**

### CODE REVIEW

**Comment by ritwik12** [comment]
@speedy-software-ch What should I look for when executing your code?It gives the same output

**Comment by speedy-software-ch** [comment]
there is no change in the output. I just changed the implementation from _system("curl wttr.in")_ to using libcurl as used in the restaurants functionality committed lately. so i used curl_easy_setopt() to set all the parameters for the get request, and then executed the request, and printed the results to the screen. I also made a special function for all this functionality, so we could at some point extract it into a separate file if we wanted to. For result processing you need to create a Struct with this two properties , which i named "string" and a callback function for memory writing. "init string()" just initializes the struct to be able to get the data returned from the http get request.

**Comment by speedy-software-ch** [comment]
@ritwik12 Now that i think about it, we get the results of the request as a string which we print to the screen. actually we could try to evaluate that string and generating a "say" command, so there is also audio output.

**Comment by ritwik12** [comment]
@speedy-software-ch Thanks :)

**Comment by ritwik12** [comment]
@all-contributors please add @speedy-software-ch for code

**Pull request merged**
