### PR TITLE
Restaurant Feature for Virtual Assistant (Issue #9)

### PR DESCRIPTION
**Pull request by Rushikesh22**
Added code for finding nearby restaurants to main.c.
Libraries used: libcurl, JSON-C
API's used: Google geocoding API, Google Places API
Please replace my API key in find_restaurants() function with your own.
In order to compile : gcc main.c $(pkg-config --libs --cflags libcurl) -l json

### CODE REVIEW

**Comment by ritwik12** [comment]
@Rushikesh22 please mention commands to install all packages that are required

**Comment by ritwik12** [comment]
Please update readme with all the steps required and code mentioned to make it easy for users

**Comment by ritwik12** [comment]
`ritwik@HP:~/Virtual-Assistant$` gcc ai.c $(pkg-config --libs --cflags libcurl) -l json -std=c99
ai.c: In function ‘get_geolocation_callback_func’:
ai.c:19:9: warning: implicit declaration of function ‘strndup’ [-Wimplicit-function-declaration]
         *response_ptr = strndup(buffer, total);
         ^
ai.c:19:23: warning: assignment makes pointer from integer without a cast
         *response_ptr = strndup(buffer, total);
                       ^
ritwik@HP:~/Virtual-Assistant$ ./a.out
Segmentation fault (core dumped)
`
@Rushikesh22 Is it working?mine is not

**Comment by Rushikesh22** [comment]
Yes its working on my system. Still i'll check. Also i'll update the readme file.

**Comment by Rushikesh22** [comment]
Could you try to compile it without "std=c99" flag? The default standard is c90 I suppose.

**Comment by ritwik12** [comment]
let me try

**Comment by ritwik12** [comment]
Most of my features in this project requires c99

**Comment by ritwik12** [comment]
@Rushikesh22 Warnings are related to strndup, do I need to do something to use strndup ? as it is not a standard function .

**Comment by ritwik12** [comment]
@Rushikesh22 warnings are removed using -std=gnu11, but still giving segmentation fault.any idea?

**Comment by Rushikesh22** [comment]
I think strndup implementation is not available on some systems. We'll have to provide the implementation ourselves. I'll fix this and the readme update by tomorrow.

**Comment by ritwik12** [comment]
No it was my bad

**Comment by ritwik12** [comment]
Sorry , its working fine. I forgot to edit config and used your code in a different directory

**Comment by ritwik12** [comment]
@Rushikesh22 It is not working with my key.
from where do I need to get the key?
Am I getting it right from here ? https://developers.google.com/maps/documentation/geocoding/get-api-key

**Comment by ritwik12** [comment]
@Rushikesh22 When I use my key, it gives segmentation fault.
Please guide me how to create and use my key.

**Comment by ritwik12** [comment]
Also please try to clear all the checks made by travis, for that you need to edit travis.yml

**Comment by ritwik12** [comment]
@Rushikesh22 I dealt with segmentation fault, but it is not printing results.
It just says "Here are some restaurants in the area".
It will be better if you guide me steps for key

**Comment by Rushikesh22** [comment]
I have updated README.md as well as travis.yml.

**Comment by Rushikesh22** [comment]
@ritwik12, yes you can get the api key for geocoding api from this link.  https://developers.google.com/maps/documentation/geocoding/get-api-key. You will have to first login to your google developer console and create a project with any name you want. When you click on "Get Key" from above link, you will see a prompt where you need to select a project name from the drop down list.

**Comment by Rushikesh22** [comment]
Make sure the project name you select is the one created by you. Then go to https://developers.google.com/places/web-service/get-api-key and again click the "get key" button. Select the same project which you chose for geocoding API. This way the same api key can be used for both geocoding and places.

**Comment by ritwik12** [comment]
@Rushikesh22 Thanks, the key is working now.

**Comment by Rushikesh22** [comment]
@ritwik12 The travis build is failing due to json library. Can we do anything to fix it?

**Comment by ritwik12** [comment]
@Rushikesh22 Yes we can.
The travis needs to know all the languages and dependencies on which our project works.please go through travis docs if you can.

**Comment by ritwik12** [comment]
@Rushikesh22 Your work is great.
A small request, is there any chance by which we can make the output result more attractive?
Just like in the case of weather.

**Comment by ritwik12** [comment]
json/json.h is not recognised by the linux system that travis uses.
maybe there is a way by which we can do that.

**Comment by ritwik12** [comment]
I would advise to go through travis docs https://docs.travis-ci.com/

**Comment by ritwik12** [comment]
@Rushikesh22 Could you help me understand your code?

**Comment by Rushikesh22** [comment]
@ritwik12 Yes sure. Also I'll change the output and the travis.yml file by tomorrow.

**Comment by ritwik12** [comment]
@Rushikesh22 I will change the output, as all the outputs should be of same color and also it should be of a popular place like new york or something.The place that everyone knows

**Comment by Rushikesh22** [comment]
@ritwik12 travis.yml is done. I can try to make the output look better if you want.

**Comment by ritwik12** [comment]
@Rushikesh22 Great work.
Yes please try to make it look better if you can.That will make it perfect

**Comment by ritwik12** [comment]
And please explain me the working of your Algorithm.

**Comment by Rushikesh22** [comment]
@ritwik12 I've improved the output format. Please check it out.

**Comment by Rushikesh22** [comment]
And I'll explain you the algorithm

**Comment by ritwik12** [comment]
@Rushikesh22 It's great, is it possible to have it multicolored?

**Comment by ritwik12** [comment]
@Rushikesh22 I have troubled you enough, let's merge it.

**Comment by ritwik12** [comment]
@Rushikesh22 Thank you so much for your effort and this great contribution.
Looking forward for more contribution from you in future :)

**Comment by ritwik12** [comment]
@Rushikesh22 Also please explain me the Algo now.

**Comment by ritwik12** [comment]
@Rushikesh22 Please run the code again as I've replaced api key to mine.Please make sure it is running fine

**Comment by Rushikesh22** [comment]
@ritwik12 Thank you for accepting my contribution. Yes I would love to work on this project in the future. I don't know how to make the output coloured but i'll check. I'll explain the algo now.

**Comment by Rushikesh22** [comment]
So in the find_restaurants() function, after variable declaration, I've initialized the 'curl' variable with curl_easy_init(). If the function returns successfully, we can go on with the actual HTTP requests to the google APIs.
libcurl.h provides a number of functions for handling HTTP requests and is lightweight. This was the first time i used it so my knowledge is limited. I referred to the libcurl docs here: https://curl.haxx.se/libcurl/

So coming to the implementation, we have used two of google's API's.:-
Google Geocoding API
Google places API.

This is because the places API can only take location input as co-ordinates.
Hence the geocoding API converts the area name entered by user into co-ordinates.
These are then passed to the places API.

For each HTTP request using libcurl, we first construct the desired url string using sprintf().
curl_easy_setopt() is then used to set values of various parameters associated with the 'curl' variable.
These options include:-

- The URL

- The HTTP method (Get or Post)

- SSL certificate

- Callback function

- Variable where response will be stored

The callback function is responsible for allocating memory to the HTTP response received. The WriteMemoryCallback() function in the code does this. This is more clearly explained here: https://curl.haxx.se/libcurl/c/getinmemory.html

The structure MemoryStruct type variables will be used to hold response data after allocation of memory. The response is assumed to be char *. 

finally curl_easy_perform() makes the HTTP request. 

The google APIs return response in json format which needs to be parsed. This is done with the help of 
JSON C library (https://github.com/json-c/json-c). This library can parse json data which we have stored in a char * member inside MemoryStruct variables.
Here are some of the functions used in the code:-

- json_tokener_parse(): parses json data returning a variable of json_object type.

- json_object_array_get_idx(): returns a json_object from a json array, present at the specified array index.

- json_object_object_get_ex(): returns the value of a json_object when a key is specified.

- json_object_array_length(): returns the length of a json array

- json_object_get_string(): returns the value of a json_object as string.

-  json_object_get_double(): returns the value of a json_object as double.

- json_object_get_boolean(): returns the value of a json_object as boolean.

Finally I've displayed the results returned from google API in the form of tables.

**Comment by Rushikesh22** [comment]
@ritwik12 Its working fine with your API key.

**Comment by ritwik12** [comment]
@Rushikesh22 Thank you so much for explaining.
I understood the code but I am unable to understand few parts
`curl_easy_setopt(curl, CURLOPT_URL, url);
+        	curl_easy_setopt(curl, CURLOPT_HTTPGET, 1);
+        	curl_easy_setopt(curl, CURLOPT_CAPATH, "/usr/ssl/certs/crt");
+		curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);
+		
+		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);
+		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&geo);
+		
+		
+		result=curl_easy_perform(curl);
+
+		if(result!=CURLE_OK)
+		{
+			fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(result));
+
+		}`
Please explain me this

**Comment by Rushikesh22** [comment]
curl_easy_setopt() function is used to set parameters for the 'curl' variable which was initialized earlier in the code with curl_easy_init()

Here the parameters are as follows:-

- CURLOPT_URL : the URL to which http request will be sent. Here we used 'url' variable to construct the URL with sprintf().

- CURLOPT_HTTPGET : This indicates the method used for HTTP request, since here we set the HTTPGET parameter to 1, we are using GET method to send the request.

- CURLOPT_CAPATH : The path for the ssl certificate. 

- CURLOPT_FOLLOWLOCATION : This when set to 1 enables redirection to another URL on the fly.

- CURLOPT_WRITEFUNCTION : This is set to the function which will allocate memory to the data returned as HTTP response.

- CURLOPT_WRITEDATA : This is set to a variable which will store the data received as HTTP response. Here the variable is of type MemoryStruct.

Finally the HTTP request is sent using curl_easy_perform() and a result code is received. We then have to check if the request was successful.

**Comment by ritwik12** [comment]
@all-contributors please add @Rushikesh22 for code, doc and infra

**Pull request merged**
