### PR TITLE
Adding Phrases

### PR DESCRIPTION
**Pull request by varuneagle555**
I added phrases to weather and media classes for more options for users to say.

### CODE REVIEW

**Comment by ritwik12** [comment]
@varuneagle555 I can't see any changes in weather.
Also if we are adding anything in greeting class than we need to have a reply for that.As the reply doesn't suits the question.

**Comment by speedy-software-ch** [comment]
@ritwik12 i think you got confused between both  PRs concerning the classes expansion.

**Comment by speedy-software-ch** [comment]
and the same for weather? that's my PR you meant, isn't it?

**Comment by ritwik12** [comment]
@speedy-software-ch NO, I  am not confused.I am talking about weather phrases.

**Comment by speedy-software-ch** [comment]
@ritwik12 time of day on greeting resonse could be determined by clock.

**Comment by ritwik12** [comment]
@speedy-software-ch That will be great

**Comment by ritwik12** [comment]
Closing as it is irrelevant now.

**Pull request closed without merging**
