### PR TITLE
main.c:add error checking when opening config

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by ritwik12** [comment]
@andy5995 Thanks for your PR. BUt sorry I am in the mid of my exams.
I will be able to look into PRs only after a week.

**Comment by ritwik12** [comment]
@andy5995 Thanks for your PR. BUt sorry I am in the mid of my exams.
I will be able to look into PRs only after a week.

**Comment by speedy-software-ch** [comment]
how can we avoid merge conflicts in the mean time? 'cause i also want to commit some features and corrections

**Comment by ritwik12** [comment]
@andy5995  Well for that I would like you to work on the current code.As the PRs which are pending have nothing to do with new features.And If there arise a case for conflict between PRs , then I will solve it myself

**Comment by speedy-software-ch** [comment]
im @speedy-software-ch not andy5995

**Comment by ritwik12** [comment]
@speedy-software-ch  yup, I corrected that

**Comment by speedy-software-ch** [comment]
ok, so i work on "main.c" and "config". gmail function is coming, as well as correction for the case "stop" is written, or empty string. does a google search for "stop" or "" right now, which is annoying.

**Comment by ritwik12** [comment]
@speedy-software-ch Typing stop should close the program, isn't it working?

**Comment by speedy-software-ch** [comment]
no it doesn't anymore, since the artificial intelligence part you committed i think.

**Comment by ritwik12** [comment]
@speedy-software-ch Ohk, then  it should be corrected. Either you do or I will do it later.

**Comment by andy5995** [comment]
>I will be able to look into PRs only after a week.

Thank you for notifying me. I will wait to submit more pull requests. Good luck with your exams. :)

**Comment by ritwik12** [comment]
@andy5995 Thanks :)

**Pull request merged**
