### PR TITLE
add configure script and Makefiles

### PR DESCRIPTION
**Pull request by andy5995**
This builds on my system (Debian 9). I don't have a libjson0-dev
package, but a libjson-c-dev package. I added include dirs to the
Makefile and took out the path from main.c

### CODE REVIEW

**Comment by andy5995** [comment]
This won't pass the travis build because I changed the line in main

`include <json/json.h>` to `include <json.h>`

I added the include search path to the Makefile though, so json.h is found.

libjson0-dev was not shipped with Debian 9; I'm using libjson-c-dev, which put json.h in the /usr/include/json-c/ directory.

**Comment by andy5995** [comment]
Most of the files included with this PR were automatically generated. You'll want to primarily examine configure.ac and Makefile.am.

**Comment by speedy-software-ch** [comment]
i had the same problem with ubuntu 17.10.

**Comment by speedy-software-ch** [comment]
how did you generate this files? anjuta project created around the source file main.c?

**Comment by andy5995** [comment]
>how did you generate this files?

@speedy-software-ch , I made a small [configure.ac](https://www.gnu.org/software/automake/manual/html_node/Creating-amhello.html#Creating-amhello) and [Makefile.am](https://www.gnu.org/software/automake/manual/html_node/Creating-amhello.html) , then used [autoreconf -ivf](https://www.gnu.org/software/autoconf/autoconf.html) and [automake](https://www.gnu.org/software/automake/)

**Comment by speedy-software-ch** [comment]
I'll try to understand what it all does

**Comment by ritwik12** [comment]
@andy5995 Give me some time to understand this.

**Comment by andy5995** [comment]
>Give me some time to understand this.

Yes, of course. :)

Perhaps a better way I should have done my pull request would have been to only add configure.ac and Makefile.am. Then there are only those 2 files; you would run `autoreconf -ivf` and `automake` and get the extra files locally.

There is a complaint about required files

```
/README
/COPYING
/AUTHORS
/ChangeLog
/NEWS
```

I used `touch` to create blank ones, and then added them to .gitignore.

But one of the easiest way for you to check my patch is copy configure.ac and Makefile.am, and after you have examined them, run the autoreconf and automake command as I mentioned above.

**Comment by ritwik12** [comment]
@andy5995 Alright, I will do that. Thanks for PR.
I am in the mid of my End semesters so it will take me some time.
Sorry for the delay.
And please configure travis.yml too so that PR will pass tests.

**Comment by ritwik12** [comment]
@andy5995 Please remove all the files that are not required or automatically generated

**Comment by ritwik12** [comment]
@andy5995 Why do we need this PR?

**Comment by andy5995** [comment]
It helps the end-user specify build options and makes it easier for maintainers to add build options as the program grows.

And in the case of our libjson-c problem, the configure script will check the users system and add the appropriate library to LDFLAGS.

Later, if you want to add international support using [gettext](https://www.gnu.org/software/gettext/), a configure.ac and Makefile.am will be much-needed.

Definitions such as SYSCONFDIR will be added to config.h, and then can be used within the program (once config.h is #included in main.c). So you won't have to guess as to where a configuration file is. If the user specifies the path using the ./configure script, it will be added to config.h and you can use that definition in your program.

**Comment by andy5995** [comment]
You can get the generated files by running these 3 commands

    aclocal -I m4
    autoreconf -ivf
    automake

**Comment by andy5995** [comment]
Once your configure script is generated, you can run `./configure --help | less` to view the different compile-time options a user can give.

**Comment by ritwik12** [comment]
@andy5995 Please guide me how can I test your changes.

**Comment by andy5995** [comment]
While in the Virtual Assistant source directory:

```
git checkout -b andy5995-create-autofiles

git pull https://github.com/andy5995/Virtual-Assistant create_autofiles

aclocal -I m4

autoreconf -ivf

```

When autoreconf is finished, you'll see some errors about required files, such as NEWS and README. just use `touch NEWS README` to create blank files. You don't have to add them to your distribution.

Then re-run `autoreconf -ivf`. That will also run automake so you can skip that this time.

When that's done, you'll see your new files. You'll see that main.c hasn't been altered.
Run `./configure` then `make`.  During make, you'll see the options passed to `gcc` to build Virtual Assistant and can verify that things are happening the way you want them to happen.

**Comment by speedy-software-ch** [comment]
can this makefile also help us getting the project into a comfortable IDE? I tried with eclipse for C/C++.

**Comment by andy5995** [comment]
I don't know. I use geany for my IDE and load all the source files when i do my coding.

**Comment by andy5995** [comment]
The Makefile.am included with this PR isn't an actual Makefile, by the way. That would get generated after ./configure is run. It would just be `Makefile` with no extension.

**Pull request closed without merging**
