### PR TITLE
Issue #38: Replacing nested IF/ELSE block with loop

### PR DESCRIPTION
**Pull request by rthugh02**
I created a struct to hold the name of the class and the score that was calculated in the already existing for loops. Then put them in an array that I iterate over to determine the max, and pass the max's name to the result.

### CODE REVIEW

**Comment by ritwik12** [comment]
@rthugh02 This looks really good and clean

**Comment by ritwik12** [comment]
@rthugh02 Good approach but I tested your code and I noticed that it is giving priority to weather functionality in most of the cases.

**Comment by rthugh02** [comment]
Looking over it that's to be expected given that the default max is set to be the weather struct. If it's favoring weather, then it must be that the weather score is zero or equal to another classes' score. I will begin designing a change to account for this bias.

**Comment by speedy-software-ch** [comment]
@rthugh02 why wouldn't we actually work with a switch() with a default section not favoring any option?

**Comment by rthugh02** [comment]
> @rthugh02 why wouldn't we actually work with a switch() with a default section not favoring any option?

Switch cases can only compare based on exact values, not conditions.

**Comment by pavan-pan** [comment]
Is this issue resolved ? can i take it up ?

**Comment by ritwik12** [comment]
@pavan-pan You can take this up as it's still not resolved.

**Comment by ritwik12** [comment]
Closing this due to lack of Activity!!

**Pull request closed without merging**
